<?php

declare(strict_types=1); // Enforce strict type checking

namespace App\Errors;

use Exception;
use Throwable;

/**
 * NotImplementedException
 *
 * A custom exception that automatically generates a helpful message when a
 * method or function is called but has not yet been implemented.
 *
 * Advantages:
 *   - Keeps the reflection logic in one place (DRY).
 *   - No need to repeat the same throw-statement code in every function.
 *   - Allows an optional custom message if desired.
 *   - Keeps throwing code minimalistic.
 */
class NotImplementedException extends Exception
{
    /**
     * __construct
     *
     * The constructor mirrors the parent `Exception` constructor but
     * automatically creates a default message describing where the
     * exception was thrown if no custom message is supplied.
     *
     * @param  string      $message   Optional custom message. If omitted,
     *                                a message is generated from the
     *                                calling context.
     * @param  Throwable   $previous  Optional previous exception (for chaining).
     * @return void
     */
    public function __construct(string $message = '', ?Throwable $previous = null)
    {
        // If the caller did not supply a message, generate one that includes
        // the class/method/function name, file, and line number.
        if (empty($message)) {
            $message = $this->generateMessage();
        }

        // Call the parent constructor with the possibly autogenerated
        // message, a code of 0, generic, and the previous throwable if any.
        parent::__construct($message, 0, $previous);
    }

    /**
     * generateMessage
     *
     * Builds a descriptive error message by inspecting the back-trace.
     *
     * @return string  The auto-generated message.
     */
    private function generateMessage(): string
    {
        // Grab a back-trace with at most 2 frames and ignore argument values,
        // DEBUG_BACKTRACE_IGNORE_ARGS keeps the trace small and safe.
        $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 2);

        // $trace[0] is this method itself.
        // $trace[1] is the caller, the function or method that triggered the exception.
        // If the caller frame is missing, fall back to the current frame.
        $caller = $trace[1] ?? $trace[0];

        // Extract the relevant pieces of information, falling back to 'unknown'
        // if any key is absent.
        $function = $caller['function'] ?? 'unknown';
        $file     = $caller['file'] ?? 'unknown';
        $line     = $caller['line'] ?? 'unknown';
        $class    = $caller['class'] ?? null;

        // If the caller is a method inside a class, format a method-specific message.
        if ($class) {
            return sprintf(
                "The method '%s::%s' (file: %s, line: %d) it is not implemented yet",
                $class,
                $function,
                $file,
                $line
            );
        }

        // Otherwise the caller was a standalone function, format accordingly.
        return sprintf(
            "The function '%s' (file: %s, line: %d) it is not implemented yet",
            $function,
            $file,
            $line
        );
    }
}
